<?php

declare(strict_types=1);

/**
 * @file
 * Provides a propertyfile entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function propertyfile_theme(): array {
  return [
    'propertyfile' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for propertyfile templates.
 *
 * Default template: propertyfile.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the propertyfile information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_propertyfile(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function propertyfile_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish propertyfiles.
      $storage = \Drupal::entityTypeManager()->getStorage('propertyfile');
      $propertyfile_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($propertyfile_ids) as $propertyfile) {
        $propertyfile->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize propertyfiles.
      $storage = \Drupal::entityTypeManager()->getStorage('propertyfile');
      $propertyfile_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($propertyfile_ids) as $propertyfile) {
        $propertyfile->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function propertyfile_user_predelete(UserInterface $account): void {
  // Delete propertyfiles that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('propertyfile');
  $propertyfile_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($propertyfile_ids)
  );
}
