<?php declare(strict_types = 1);

/**
 * @file
 * Provides a booking entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function booking_theme(): array {
  return [
    'booking' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for booking templates.
 *
 * Default template: booking.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the booking information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_booking(array &$variables): void {
  $variables['view_mode'] = (isset($variables['elements']['#view_mode'])) ? $variables['elements']['#view_mode'] : '';
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function booking_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish bookings.
      $storage = \Drupal::entityTypeManager()->getStorage('booking');
      $booking_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($booking_ids) as $booking) {
        $booking->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize bookings.
      $storage = \Drupal::entityTypeManager()->getStorage('booking');
      $booking_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($booking_ids) as $booking) {
        $booking->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function booking_user_predelete(UserInterface $account): void {
  // Delete bookings that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('booking');
  $booking_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($booking_ids)
  );
}
