<?php 

function sr_quotation_theme($existing, $type, $theme, $path) {
  $module_handler = \Drupal::service('extension.list.module');
  $module_path = $module_handler->getPath('sr_quotation');
  return [
    'quotation_form' => [
      'render element' => 'form',
      'template' => 'quotation-form',
      'library' => [
        'sr_quotation/quotation-form',
      ],
    ],
    'quotation_dashboard' => [
      'variables' => [
        'quotations' => [],
        'add_link' => NULL,
      ],
      'template' => 'quotation-dashboard',
      // 'path' => drupal_get_path('module', 'sr_quotation') . '/templates',
    ],
    'pdf__quotation' => [
      'variables' => [
        'record' => NULL,
        'image_urls' => [],
      ],
      'template' => 'pdf--quotation',
      'path' => $module_path . '/templates',
    ],
  ];
}
