<?php

declare(strict_types=1);

/**
 * @file
 * Provides a propertyvendor entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function propertyvendor_theme(): array {
  return [
    'propertyvendor' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for propertyvendor templates.
 *
 * Default template: propertyvendor.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the propertyvendor information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_propertyvendor(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function propertyvendor_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish propertyvendors.
      $storage = \Drupal::entityTypeManager()->getStorage('propertyvendor');
      $propertyvendor_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($propertyvendor_ids) as $propertyvendor) {
        $propertyvendor->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize propertyvendors.
      $storage = \Drupal::entityTypeManager()->getStorage('propertyvendor');
      $propertyvendor_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($propertyvendor_ids) as $propertyvendor) {
        $propertyvendor->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function propertyvendor_user_predelete(UserInterface $account): void {
  // Delete propertyvendors that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('propertyvendor');
  $propertyvendor_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($propertyvendor_ids)
  );
}
